### ISSUE TITLE
"Pending Membership Score" doesn't make sense after paying membership dues

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#224]
![Skärmavbild 2021-03-18 kl  14 11 27](https://user-images.githubusercontent.com/9698363/111752345-e0536b00-8895-11eb-9b1d-4afa30343dcf.png)

The new header "Pending Membership Score" sounds right before paying dues. After paying dues perhaps that box should disappear completely?

**Comment by GriffGreen** [comment]
@kristoferlund Yes please! Can we make the box disappear after they pay the dues? @markoprljic think we should just extend the box down?

**Comment by markoprljic** [comment]
I just received an email from CS inviting me to join the TSA but I think I already paid membership dues. When I open the link from the email, connect my wallet, I still see the button "Pay membership dues". Now I'm confused because I can't remember anymore, I think this is the TX https://etherscan.io/tx/0xf9c71cb656fca1add7f8e8059826f3ee292149feff8664fe12d603a0f4f444a9 

Having said that, I think that in addition to **Pending Membership Score** also the button **Pay membership dues** should be removed and instead information displayed like in the mockup below...

![Image 2021-03-23 at 6 57 15 am](https://user-images.githubusercontent.com/5704285/112100213-0f732080-8ba5-11eb-855c-117532f6a85b.jpg)

This is the screen in Figma (used for pending transaction but can be used for success as well) https://www.figma.com/file/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=1459%3A0

**Comment by GriffGreen** [comment]
@markoprljic, we want people to be able to pay MORE membership dues... this will be the main way we collect funds from our community... but that said, we could change the page so that it shows that the person is an official member of the organization.

**Comment by markoprljic** [comment]
Can we call it differently then? Instead of "Pay membership dues" to say "Top up your membership" or something else?

**Comment by tamarandom** [comment]
Update : 

1. @markoprljic your idea makes a lot of sense. 

On the screen we currently use, ![Screen Shot 2021-03-24 at 8.40.29 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/35878dc2-7404-43be-89de-467c1b449e5c)

"Your membership dues are paid. By paying more membership dues you will further support the mission of the organization."

2. The button should be changes to "Pay additional dues"

3. Lastly, the box on the lower left  ("your pending membership score") to be removed and the upper left box will be extended to the same length as the right side box.

**Comment by kristoferlund** [comment]
Fixed in #228, does this look ok?

![image](https://user-images.githubusercontent.com/9698363/112614134-33db3100-8e21-11eb-9896-4ea55a7c0bbb.png)
